### ISSUE TITLE
A typo in the configuration file in the parameter jwt-expire-in

### ISSUE THREAD

**Issue by cardinalit** [OscarYuen/go-graphql-example#17]
Hi, 

I am using your repository for the purpose of exploring _GraphQL_ with _Go_ and I noticed a typo in the file configuration, in the `jet-expire-in`. 

For the correct signature of the jwt, you need to remove the letter `s`.

```toml
[auth]
jwt-secret = "[you_secret_here]"    # you secret here
jwt-expire-in = "3600"              # 1 hour in seconds
```
If you do not make changes, then after reading the configuration file, the value of this parameter will take the value with the letter and the output after conversion to `Unix()` you will get a completely different value than 1 hour.

You can check it: try to logging the parameter after read configuration file.
